<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="InicioEj1.aspx.cs" Inherits="principalForm.formEjercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style>
        .Ej2
        {
            margin-top: 1rem;
            font-family: Dubai;
            justify-content:center;
            text-align: center;
        }
        .Buttons
        {
            margin-top: 1rem;
            margin-bottom: 1rem;
            margin-left: 2rem;
            margin-right: 2rem;
            display: inline-block;
            padding: 7px 7px;
            background-color: #5D7B9D; 
            border-radius: 5px; 
            text-decoration: none;
        }
        .Links
        {
            margin-top: 2rem;
            margin-bottom:2rem;
            text-align:center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server" class ="Ej2">
        <div class="Links">
                        <asp:Label ID="lblEjercicio1" runat="server" Text="Ejercicio N°1"></asp:Label>
        </div>
                        <asp:Label ID="lblProductos" runat="server" Enabled="False" Font-Bold="True" Font-Size="20pt" Text="Productos" BackColor="Black" ForeColor ="White" CssClass="auto-style4" Width="829px" ></asp:Label>
        <div>
                        <asp:GridView ID="grdProductos" runat="server" Height="351px" Width="831px" AutoGenerateColumns="False" AutoGenerateEditButton="True"  OnRowEditing="grdProductos_RowEditing" OnRowCancelingEdit="grdProductos_RowCancelingEdit" OnRowDeleting="grdProductos_RowDeleting" OnRowUpdating="grdProductos_RowUpdating" AutoGenerateDeleteButton="True" AllowPaging="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnPageIndexChanging="grdProductos_PageIndexChanging" HorizontalAlign="Center">
                           
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />

                            <Columns>

                                <asp:TemplateField HeaderText="ID Producto">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_eitIdProducto" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_IDProducto" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Nombre Producto">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_EITnombreProducto" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_NombreProducto" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Cantidad Por Unidad">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_EITcantidad" runat="server" Text='<%# Bind("cantidadPorUnidad") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_CantidadUnidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Precio Unidad">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_EITprecio" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_PrecioUnidad" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>

                            </Columns>

                            <EditRowStyle BackColor="#999999" />
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#E9E7E2" />
                            <SortedAscendingHeaderStyle BackColor="#506C8C" />
                            <SortedDescendingCellStyle BackColor="#FFFDF8" />
                            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />

                        </asp:GridView>
            </div>

                <div class="Links">
                <asp:HyperLink ID="hlInicio" runat="server" Font-Underline="False" NavigateUrl="~/InicioTP.aspx" ForeColor="#3399FF">Volver al Menú Principal</asp:HyperLink>
                </div>
   
        </form>
    </body>
</html>
